/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TicTacToe;

import java.awt.Color;
import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
//game
public class TicTacToeGame extends javax.swing.JFrame {
    //Attributes
    private String gameStart="x";
    private int playerXCount=0;
    private int player0Count=0;
    private String name1;
    private String name2;
    //List of players
    private ArrayList<Player> players;
    /**
     * Creates new form TicTacToeGame
     */
    
    //Constructor
    public TicTacToeGame(String name1,String name2,ArrayList<Player> players) {
        this.name1=name1;
        this.name2=name2;
        this.players=players;
        
        initComponents();
        setSize(1200,600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
                       //initialize the components    
    private void initComponents() {
//Components
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        Player0Label = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        PlayerXLabel = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        resetButton = new javax.swing.JButton();
//Set default close operation
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//initializing and seting the sizes
        jPanel1.setBackground(new java.awt.Color(204, 153, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 100)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tic Tac Toe");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);
//Adding the layout on pannel
        jPanel2.setLayout(new java.awt.GridLayout(3, 5, 2, 2));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 96)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton2.setFont(new java.awt.Font("Tahoma", 3, 96)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 3, 96)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText(this.name2);
        jPanel6.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        Player0Label.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Player0Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Player0Label.setText("0");
        jPanel7.add(Player0Label, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));
        jPanel8.setLayout(new java.awt.BorderLayout());
//Action listener on button
        jButton4.setFont(new java.awt.Font("Tahoma", 3, 96)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jButton5.setFont(new java.awt.Font("Tahoma", 3, 96)); // NOI18N
        //Action listener on button
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jButton6.setFont(new java.awt.Font("Tahoma", 3, 96)); // NOI18N
        //Action listener on button
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText(this.name1);
        jPanel11.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(204, 204, 255));
        jPanel12.setLayout(new java.awt.BorderLayout());

        PlayerXLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        PlayerXLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PlayerXLabel.setText("0");
        jPanel12.add(PlayerXLabel, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel12);

        jPanel13.setBackground(new java.awt.Color(204, 204, 255));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jButton7.setFont(new java.awt.Font("Tahoma", 3, 96)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel13);

        jPanel14.setBackground(new java.awt.Color(204, 204, 255));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jButton8.setFont(new java.awt.Font("Tahoma", 3, 96)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel14);

        jPanel15.setBackground(new java.awt.Color(204, 204, 255));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jButton9.setFont(new java.awt.Font("Tahoma", 3, 96)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton9, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel15);

        jPanel16.setBackground(new java.awt.Color(204, 204, 255));
        jPanel16.setLayout(new java.awt.BorderLayout());
//Action listener on exit button
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //Writing the data into file
                PrintWriter writer=null;
                boolean found1=false;
                boolean found2=false;
                //finding the player if exist then update the player
                for(int i=0;i<players.size();i++){
                    Player pl=players.get(i);
                    if(pl.getName().equals(jLabel2.getText())){
                        int score=pl.getScore()+Integer.parseInt(PlayerXLabel.getText());
                        //update the score of player
                        pl.setScore(score);
                       
                        found1=true;
                    }
                    if(pl.getName().equals(jLabel3.getText()))
                    {
                         int score=pl.getScore()+Integer.parseInt(Player0Label.getText());
                            //update the score of player
                        pl.setScore(score);
                         found2=true;
                    }
                }
                
                //if player not exist then add new player
                if(!found1)
                    players.add(new Player(jLabel2.getText(),Integer.parseInt(PlayerXLabel.getText())));
                if(!found2)
                    players.add(new Player(jLabel3.getText(),Integer.parseInt(Player0Label.getText())));
                try{
                    writer=new PrintWriter(new File("players.txt"));
                    for(Player p:players)
                    {//writing data into file
                        writer.write(p.toString());
                        writer.flush();
                    }
                    writer.close();
                }catch(Exception ex){
                    System.out.println(ex.getMessage());
                }
                
                exitButtonActionPerformed(evt);
            }
        });
        jPanel16.add(exitButton, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(204, 204, 255));
        jPanel17.setLayout(new java.awt.BorderLayout());

        resetButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        resetButton.setText("Reset");
        //reset button action listener
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel17.add(resetButton, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel17);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        
    private JFrame frame;
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
         // TODO add your handling code here:
         frame = new JFrame("Exit");
         if(JOptionPane.showConfirmDialog(frame, "do you want to exit", "Tic Tac Toe",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
         {
             System.exit(0);
         }
    }                                          
    private void setName(){
        
        jLabel2.setText(this.name1);
        jLabel3.setText(this.name2);
        
    }
    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
     ;
        setColor(jButton1);
        setColor(jButton2);
        setColor(jButton3);
        setColor(jButton4);
        setColor(jButton5);
        setColor(jButton6);
        setColor(jButton7);
        setColor(jButton8);
        setColor(jButton9);
    }                                           

    private void setColor(JButton btn){
        btn.setBackground(Color.GRAY);
        btn.setText("");
       
    }
    
    //action listener on each button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jButton1.setText(gameStart);
        if(gameStart.equalsIgnoreCase("x")){
           jButton1.setForeground(Color.yellow);
           
        }else{
            jButton1.setForeground(Color.blue);
        }
        choose_a_player();
        gameWinner();
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jButton2.setText(gameStart);
        if(gameStart.equalsIgnoreCase("x")){
           jButton2.setForeground(Color.yellow);
           
        }else{
            jButton2.setForeground(Color.blue);
        }
        choose_a_player();
        gameWinner();
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jButton3.setText(gameStart);
        if(gameStart.equalsIgnoreCase("x")){
           jButton3.setForeground(Color.yellow);
           
        }else{
            jButton3.setForeground(Color.blue);
        }
        choose_a_player();
        gameWinner();
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jButton4.setText(gameStart);
        if(gameStart.equalsIgnoreCase("x")){
           jButton4.setForeground(Color.yellow);
           
        }else{
            jButton4.setForeground(Color.blue);
        }
        choose_a_player();
        gameWinner();
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jButton5.setText(gameStart);
        if(gameStart.equalsIgnoreCase("x")){
           jButton5.setForeground(Color.yellow);
           
        }else{
            jButton5.setForeground(Color.blue);
        }
        choose_a_player();
        gameWinner();
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jButton6.setText(gameStart);
        if(gameStart.equalsIgnoreCase("x")){
           jButton6.setForeground(Color.yellow);
           
        }else{
            jButton6.setForeground(Color.blue);
        }
        choose_a_player();
        gameWinner();
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jButton7.setText(gameStart);
        if(gameStart.equalsIgnoreCase("x")){
           jButton7.setForeground(Color.yellow);
           
        }else{
            jButton7.setForeground(Color.blue);
        }
        choose_a_player();
        gameWinner();
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jButton8.setText(gameStart);
        if(gameStart.equalsIgnoreCase("x")){
           jButton8.setForeground(Color.yellow);
           
        }else{
            jButton8.setForeground(Color.blue);
        }
        choose_a_player();
        gameWinner();
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        jButton9.setText(gameStart);
        if(gameStart.equalsIgnoreCase("x")){
           jButton9.setForeground(Color.yellow);
           
        }else{
            jButton9.setForeground(Color.blue);
        }
        choose_a_player();
        gameWinner();
    }                                        

    private void gameWinner(){
        String b1Text=jButton1.getText();
        String b2Text=jButton2.getText();
        String b3Text=jButton3.getText();
        String b4Text=jButton4.getText();
        String b5Text=jButton5.getText();
        String b6Text=jButton6.getText();
        String b7Text=jButton7.getText();
        String b8Text=jButton8.getText();
        String b9Text=jButton9.getText();
        //match the players entries if in a row or in diagonal then player wins
        if(b1Text.equals("x") && b2Text.equals("x") && b3Text.equals("x")){
            JOptionPane.showMessageDialog(this, jLabel2.getText(), "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            playerXCount++;
            gameScore();
            jButton1.setBackground(Color.green);
            jButton2.setBackground(Color.green);
            jButton3.setBackground(Color.green);
        
    }
        if(b4Text.equals("x") && b5Text.equals("x") && b6Text.equals("x")){
            JOptionPane.showMessageDialog(this, jLabel2.getText(), "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            playerXCount++;
            gameScore();
            jButton4.setBackground(Color.MAGENTA);
            jButton5.setBackground(Color.MAGENTA);
            jButton6.setBackground(Color.MAGENTA);
        
    }
        
        if(b7Text.equals("x") && b8Text.equals("x") && b9Text.equals("x")){
            JOptionPane.showMessageDialog(this, jLabel2.getText(), "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            playerXCount++;
            gameScore();
            jButton7.setBackground(Color.gray);
            jButton8.setBackground(Color.gray);
            jButton9.setBackground(Color.gray);
        
    }
          
                
                if(b1Text.equals("o") && b2Text.equals("o") && b3Text.equals("o")){
            JOptionPane.showMessageDialog(this, jLabel3.getText(), "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            player0Count++;
            gameScore();
            jButton1.setBackground(Color.orange);
            jButton2.setBackground(Color.orange);
            jButton3.setBackground(Color.orange);
        
    }
        if(b1Text.equals("o") && b5Text.equals("o") && b9Text.equals("o")){
            JOptionPane.showMessageDialog(this, jLabel3.getText(), "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            player0Count++;
            gameScore();
            jButton1.setBackground(Color.blue);
            jButton5.setBackground(Color.blue);
            jButton9.setBackground(Color.blue);
        
    }
        if(b1Text.equals("x") && b5Text.equals("x") && b9Text.equals("x")){
            JOptionPane.showMessageDialog(this, jLabel2.getText(), "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            playerXCount++;
            gameScore();
            jButton1.setBackground(Color.orange);
            jButton5.setBackground(Color.orange);
            jButton9.setBackground(Color.orange);
        
    }
       
        
        
        
        if(b3Text.equals("o") && b5Text.equals("o") && b7Text.equals("o")){
            JOptionPane.showMessageDialog(this, jLabel3.getText(), "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            player0Count++;
            gameScore();
            jButton3.setBackground(Color.blue);
            jButton5.setBackground(Color.blue);
            jButton7.setBackground(Color.blue);
        
    }
        
        
        
         if(b4Text.equals("o") && b5Text.equals("o") && b6Text.equals("o")){
            JOptionPane.showMessageDialog(this,jLabel3.getText() , "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            player0Count++;
            gameScore();
            jButton4.setBackground(Color.blue);
            jButton5.setBackground(Color.blue);
            jButton6.setBackground(Color.blue);
        
    }
        
        
        if(b7Text.equals("o") && b8Text.equals("o") && b9Text.equals("o")){
            JOptionPane.showMessageDialog(this, jLabel3.getText(), "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            player0Count++;
            gameScore();
            jButton7.setBackground(Color.white);
            jButton8.setBackground(Color.white);
            jButton9.setBackground(Color.white);
        
    }
        
        
        
        if(b3Text.equals("x") && b5Text.equals("x") && b7Text.equals("x")){
            JOptionPane.showMessageDialog(this,jLabel2.getText() , "Tic Tac Toe", JOptionPane.INFORMATION_MESSAGE);
            playerXCount++;
            gameScore();
            jButton3.setBackground(Color.white);
            jButton5.setBackground(Color.white);
            jButton7.setBackground(Color.white);
        
    }
        
    }
    private void gameScore(){
        PlayerXLabel.setText(String.valueOf(player0Count));
        Player0Label.setText(String.valueOf(playerXCount));
        
    }
    
    private void choose_a_player()
    {
        if(gameStart.equalsIgnoreCase("x")){
            gameStart="o";
           
        }else{
            gameStart="x";
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TicTacToeGame().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify                     
    private javax.swing.JLabel Player0Label;
    private javax.swing.JLabel PlayerXLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton resetButton;
    // End of variables declaration                   
}